from __future__ import annotations
import argparse,hashlib,json,shutil,subprocess
from pathlib import Path
from phase6hl_guard_preflight import _read_bounded,build_guard_command
from phase6hm_process_role_fixture import _read_jsonl
from phase6hn_process_tree_topology import validate_trace_roles
from phase6ho_app_ready_environment import ROOT,write_json
from phase6ho_process_tree_topology import APP,KIT
from phase6hr_lifecycle_classification import consume_guard_report
import phase6ih_runtime_authoring_isolation as isolation
from run_phase6hz_import_smoke import hashes as invariant_hashes
S=ROOT/"scripts";CONTRACT=S/"phase6ih_runtime_authoring_isolation_contract.json";SIDECAR=S/"phase6ih_runtime_authoring_isolation_contract.sha256";PYTHON=Path(r"C:\Python38\python.exe");GUARD=S/"phase6hr_resource_guard.py";CASE=S/"run_phase6ih_runtime_authoring_isolation_case.ps1";PROBE=S/"probe_phase6ih_runtime_authoring_isolation.py"
def run(root:Path,preflight_path:Path)->dict:
 if root.exists():raise RuntimeError("Phase 6IH runtime refuses root reuse")
 digest=hashlib.sha256(CONTRACT.read_bytes()).hexdigest().upper();policy=json.loads(CONTRACT.read_text());preflight=_read_bounded(preflight_path)
 if digest!=SIDECAR.read_text().split()[0].upper() or preflight.get("status")!="qualified" or preflight.get("contract_sha256")!=digest:raise RuntimeError("Phase 6IH preflight/contract invalid")
 root.mkdir(parents=True);attempt=root/"attempt01";logs=attempt/"runner-logs";logs.mkdir(parents=True)
 for source,target in ((CONTRACT,"frozen_contract.json"),(SIDECAR,"frozen_contract.sha256"),(S/"phase6ih_authoring_dependencies.json","frozen_dependency_manifest.json"),(S/"phase6ih_authoring_dependencies.sha256","frozen_dependency_manifest.sha256")):shutil.copy2(source,root/target)
 before=invariant_hashes();attempt_id="phase6ih-runtime-authoring-isolation-attempt01";paths={"output":attempt/"isolation_audit.json","markers":attempt/"markers.jsonl","runner_evidence":attempt/"runner_evidence.json","kit_log":attempt/"kit.log","kit_stdout":attempt/"kit.stdout.log","kit_stderr":attempt/"kit.stderr.log","trace":logs/"resource.jsonl","summary":logs/"guard.json","child_stdout":logs/"powershell.stdout.log","child_stderr":logs/"powershell.stderr.log","cleanup":logs/"cleanup.jsonl","lifecycle":attempt/"isolation_audit.json","gpu":logs/"gpu.csv"}
 ps=Path(r"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe");target=[str(ps),"-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-File",str(CASE),"-KitPath",str(KIT),"-AppPath",str(APP),"-ProbePath",str(PROBE),"-MarkersPath",str(paths["markers"]),"-AuditPath",str(paths["output"]),"-StageRoot",str(attempt/"generated-stages"),"-RunnerEvidencePath",str(paths["runner_evidence"]),"-ContractPath",str(CONTRACT),"-KitLogPath",str(paths["kit_log"]),"-KitStdoutPath",str(paths["kit_stdout"]),"-KitStderrPath",str(paths["kit_stderr"]),"-AttemptId",attempt_id];write_json(attempt/"launch_contract.json",{"schema":"campfire.phase6ih.launch.v1","phase":"phase6ih","attempt_id":attempt_id,"target":target,"cwd":str(ROOT),"timeline_play_calls":0})
 command=build_guard_command(PYTHON,GUARD,paths,target,attempt_id=attempt_id,safety=policy["safety"],include_gpu=True);i=command.index("--");command[i:i]=["--runner-evidence-path",str(paths["runner_evidence"]),"--marker-path",str(paths["markers"]),"--contract-path",str(CONTRACT),"--mode","smoke"]
 with (logs/"guard-launcher.stdout.log").open("wb",buffering=0) as out,(logs/"guard-launcher.stderr.log").open("wb",buffering=0) as err:p=subprocess.Popen(command,cwd=ROOT,stdout=out,stderr=err,creationflags=getattr(subprocess,"CREATE_NO_WINDOW",0));guard_exit=p.wait()
 guard=_read_bounded(paths["summary"]) if paths["summary"].is_file() else {};audit=_read_bounded(paths["output"]) if paths["output"].is_file() else {};runner=_read_bounded(paths["runner_evidence"]) if paths["runner_evidence"].is_file() else {};samples=_read_jsonl(paths["trace"]) if paths["trace"].is_file() else [];roles_ok,role_failures,roles=validate_trace_roles(samples);canonical=consume_guard_report(guard,policy,expected_attempt_id=attempt_id);cleanup=guard.get("observed_process_cleanup") or {};after=invariant_hashes();markers=runner.get("marker_names") or []
 docs=[];document_validation=[]
 for boundary in isolation.BOUNDARIES:
  try:value=isolation.read_document(attempt/(boundary+"_isolation_snapshot.json"));docs.append(value);document_validation.append({"boundary":boundary,"accepted":True,"snapshot_sha256":value["snapshot_sha256"]})
  except Exception as error:document_validation.append({"boundary":boundary,"accepted":False,"error":f"{type(error).__name__}:{error}"})
 sequence=isolation.validate_sequence(docs) if len(docs)==4 else {"accepted":False,"classification":"safe_stop_runtime_authoring_isolation_failure","reasons":["snapshot_count_invalid"]};operation=audit.get("operation_complete") is True and sequence.get("accepted") is True;lifecycle=bool(audit.get("shutdown_complete") is True and (audit.get("lifecycle") or {}).get("stage_close_complete") is True and runner.get("process_exit_code")==0 and canonical.get("accepted") and cleanup.get("all_observed_absent") is True);markers_ok=all(name in markers for name in policy["runtime"]["required_markers"]);qualified=operation and lifecycle and markers_ok and roles_ok and before==after and not runner.get("fatal_lines") and not runner.get("dump_inventory") and not runner.get("automatic_upload_attempt_lines")
 result={"schema":"campfire.phase6ih.summary.v1","phase":"phase6ih","status":"runtime_authoring_isolation_qualified" if qualified else "safe_stop_runtime_authoring_isolation_failure","contract_sha256":digest,"kit_launch_count":1,"retry_count":0,"replacement_count":0,"guard_exit_code":guard_exit,"operation_evidence_complete":operation,"lifecycle_complete":lifecycle,"document_validation":document_validation,"sequence_validation":sequence,"runtime_record_counts":{row["boundary"]:len(row["runtime_records"]) for row in docs},"layer_states":{row["boundary"]:{role:{k:data.get(k) for k in ("identifier","dirty","file_sha256","memory_export_sha256","memory_export_bytes")} for role,data in row["layers"].items()} for row in docs},"last_marker":markers[-1] if markers else None,"required_markers_complete":markers_ok,"kit_exit_code":runner.get("process_exit_code"),"canonical_lifecycle_classification":canonical.get("classification"),"canonical_consumer_reason":canonical.get("reason"),"resource_peaks_bytes":guard.get("peaks",{}),"resource_minima_bytes":guard.get("machine_minima",{}),"roles_pass":roles_ok,"roles":roles,"role_failures":role_failures,"exact_cleanup_all_absent":cleanup.get("all_observed_absent") is True,"residual_process_count":0 if cleanup.get("all_observed_absent") is True else None,"fatal_lines":runner.get("fatal_lines") or [],"dump_inventory":runner.get("dump_inventory") or [],"automatic_upload_attempt_lines":runner.get("automatic_upload_attempt_lines") or [],"invariants_pass":before==after,"invariant_hashes_before":before,"invariant_hashes_after":after,"phase6ig_reclassified":False,"phase6ig_artifact_or_runtime_reused":False,"production_changed":False,"defaults_changed":False,"point_policy_changed":False,"v3_changed":False,"latest_demo_changed":False};write_json(root/"summary.json",result);return result
def main():
 p=argparse.ArgumentParser();p.add_argument("--artifact-root",type=Path,required=True);p.add_argument("--preflight-summary",type=Path,required=True);args=p.parse_args();return 0 if run(args.artifact_root.absolute(),args.preflight_summary.absolute())["status"]=="runtime_authoring_isolation_qualified" else 1
if __name__=="__main__":raise SystemExit(main())
