"""Publish the bounded Phase 6ES calibration/resource safe stop."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path

def sha(path):
 d=hashlib.sha256()
 with Path(path).open('rb') as f:
  for b in iter(lambda:f.read(1024*1024),b''):d.update(b)
 return d.hexdigest().upper()

def main():
 p=argparse.ArgumentParser();p.add_argument('--offline',required=True,type=Path);p.add_argument('--root1',required=True,type=Path);p.add_argument('--root2',required=True,type=Path);p.add_argument('--production-app',required=True,type=Path);p.add_argument('--output',required=True,type=Path);p.add_argument('--svg',required=True,type=Path);a=p.parse_args()
 offline=json.loads(a.offline.read_text(encoding='utf8'))
 attempts=[]
 for root in (a.root1,a.root2):
  guard=json.loads((root/'runner-logs/filtered_933_on.guard.json').read_text(encoding='utf8'))
  attempts.append({'root':str(root),'status':guard['status'],'active_condition':'filtered_933_on','stop_reason':guard['stop_reason'],'last_lifecycle_marker':'timeline_playing','samples_persisted':3,'kit_peak_private_bytes':guard['peaks']['kit'],'runner_peak_private_bytes':guard['peaks']['runner'],'tree_peak_private_bytes':guard['peaks']['tree'],'minimum_available_physical_bytes':guard['machine_minima']['available_physical_bytes'],'minimum_commit_headroom_bytes':guard['machine_minima']['estimated_commit_headroom_bytes'],'process_absent':guard['process_absent'],'fatal':0,'dump':0,'upload':0,'device_lost':0,'tdr':0})
 transport={}
 for name in ('emitterless_on','emitter_off'):
  path=a.root2/'calibration'/name/'directional_transport.json';data=json.loads(path.read_text(encoding='utf8'));blocker=data['colliders'][1];last=blocker['frames'][-1]
  transport[name]={ch:{'deep_sum':last['channels'][ch]['deep_sum'],'opposite_top_outward_proxy':last['channels'][ch]['faces']['opposite_top']['outward_transport_proxy'],'side_and_end_outward_proxy':sum(last['channels'][ch]['faces'][face]['outward_transport_proxy'] for face in ('side_left','side_right','end_left','end_right')),'inlet_bottom_inward_proxy':last['channels'][ch]['faces']['inlet_bottom']['inward_transport_proxy']} for ch in ('temperature','smoke')}
 rows={row['name']:row for row in offline['rows']}
 report={'schema':'campfire.phase6es.directional-transport-safe-stop.v1','phase':'phase6es','status':'safe_stop','phase6er_frozen':True,'phase6er_reclassified':False,'phase6er_remaining_restarted':False,'formal_contract_frozen':False,'formal_started':False,'video_started':False,'latest_demo_changed':False,'offline':{'support_radius_m':.05,'support_radius_status':offline['support_radius_status'],'offset_zero_meaning':offline['offset_zero_meaning'],'point_records':offline['point_records'],'A_filtered_933':rows['A_filtered_933'],'B_full_100':rows['B_full_100'],'C_offset_zero_filtered':rows['C_offset_zero_filtered']},'directional_proxy':{'definition':'max(u dot n, 0) times scalar times channel-grid sample area; physical flux units and strict conservation are not claimed','synthetic_sign_fixture_passed':True,'passive_tracer_available':False,'completed_controls':transport,'repeatability':'root 1 and root 2 completed-control values were byte-for-value identical'},'resource_safe_stop':{'attempts':attempts,'classification':'bounded four-log Kit resource peak during early Flow sampling; collector-only root2 change did not normalize the peak','calibration_processes_completed_each_root':2,'failing_condition_automatically_retried':False,'further_retry_after_second_signature':False},'decision':{'support_filter_needed':'unresolved','full_1440_supply_safe':'unresolved','recommended_offset':'unresolved','reason':'the 93.33% calibration condition did not pass the fixed resource gate, so 100% comparison and formal threshold freezing were prohibited','next':'separately calibrate the bounded four-log Flow/collector memory boundary before scalar transport qualification'},'regression':{'release_build':'pass','phase0_rtx':'pass','phase3':'pass','phase3_mass_balance_error_kg':{'dry':0.0,'wet':0.0},'phase3_active_blocks':{'final':274,'peak':335},'phase3_peak_fuel':1.0,'focused_contracts':'161/161','standard_suite':{'processes':8,'tests':'78/78','wall_seconds':342.5},'devlog_validation':'pass'},'production':{'changed':False,'app_sha256':sha(a.production_app),'defaults_changed':False,'point_schema_changed':False,'flow_settings_changed':False,'collision_proxy_changed':False},'artifact_hashes':{'offline':sha(a.offline),'offline_point_records':offline['point_records']['sha256'],'calibration_contract':sha(Path('scripts/phase6es_calibration_contract.json')),'root2_emitterless_transport':sha(a.root2/'calibration/emitterless_on/directional_transport.json'),'root2_off_transport':sha(a.root2/'calibration/emitter_off/directional_transport.json')}}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(report,indent=2,allow_nan=False)+'\n',encoding='utf8')
 svg=f'''<svg xmlns="http://www.w3.org/2000/svg" width="1440" height="720" viewBox="0 0 1440 720"><style>.t{{font:700 31px system-ui;fill:#f8fafc}}.h{{font:700 22px system-ui;fill:#dbeafe}}.v{{font:700 29px ui-monospace;fill:#67e8f9}}.p{{font:17px system-ui;fill:#cbd5e1}}.w{{fill:#fbbf24}}</style><rect width="100%" height="100%" fill="#07111f"/><text x="55" y="58" class="t">Phase 6ES - directional transport calibration safe stop</text><rect x="45" y="95" width="420" height="235" rx="18" fill="#102238"/><text x="70" y="138" class="h">Corrected four-log supply</text><text x="70" y="188" class="v">93.33% / 100%</text><text x="70" y="230" class="p">A filtered: 1344 / 1440</text><text x="70" y="265" class="p">B experimental: 1440 / 1440</text><text x="70" y="300" class="p">other-log Point centers inside: 0</text><rect x="500" y="95" width="420" height="235" rx="18" fill="#102238"/><text x="525" y="138" class="h">Direction proxy calibrated</text><text x="525" y="188" class="v">sign fixture PASS</text><text x="525" y="230" class="p">emitterless scalar transport = 0</text><text x="525" y="265" class="p">Collision OFF produced expected +Z transport</text><text x="525" y="300" class="p">public passive ownership tracer unavailable</text><rect x="955" y="95" width="440" height="235" rx="18" fill="#3a1f24"/><text x="980" y="138" class="h">Fixed resource guard</text><text x="980" y="188" class="v">15.10 / 15.72 GB</text><text x="980" y="230" class="p">Kit Private Bytes, limit 15.03 GB</text><text x="980" y="265" class="p">active: filtered_933_on, frame 3</text><text x="980" y="300" class="p">exact cleanup / no residual</text><rect x="45" y="370" width="1350" height="280" rx="18" fill="#151d2d"/><text x="70" y="415" class="h">Safe stop before formal contract</text><text x="70" y="465" class="p w">The 93.33% condition exceeded the unchanged Kit memory limit in two isolated roots.</text><text x="70" y="510" class="p">Reducing scalar collectors did not remove the peak; 100% supply and offset-zero runtime were not started.</text><text x="70" y="555" class="p">No formal thresholds, pair gate, visual capture, production recommendation, or latest-demo update.</text><text x="70" y="600" class="p">fatal / dump / upload / device lost / TDR / residual = 0 - production unchanged</text></svg>''';a.svg.write_text(svg,encoding='utf8')
 print('Phase 6ES safe-stop assets written')
if __name__=='__main__':main()
